CREATE TABLESPACE ZIRAAT_TS DATAFILE 'ZIRAAT_TS.dat' size 20m 
     autoextend on next 32m maxsize UNLIMITED extent management local
     AUTOALLOCATE SEGMENT SPACE MANAGEMENT AUTO;

DROP USER ziraat CASCADE;
CREATE USER ziraat
  IDENTIFIED BY teknoloji
  DEFAULT TABLESPACE ZIRAAT_TS
  TEMPORARY TABLESPACE temp
  QUOTA unlimited on ZIRAAT_TS;

GRANT CONNECT TO ziraat;

GRANT ALL PRIVILEGES TO ziraat IDENTIFIED BY teknoloji;

GRANT RQADMIN TO ZIRAAT;
